Fix belongsTo
Askedio/laravel-soft-cascade pull request #77
Opened 2018-05-02 07:17 UTC by rybakk

2018-05-02 23:06 UTC, gcphost requested changes

2018-05-02 23:06 UTC, gcphost commented on tests/IntegrationTest.php
> +    private function createCustomerRaw()
Double paste?

2018-05-02 23:06 UTC, gcphost commented on tests/IntegrationTest.php
> +    public function testBelongsToRelation()
Here too

2018-05-03 10:46 UTC, maguilar92 commented
@gcphost I think there's no need to make package work with belongsTo relation.
The cascading must be defined in hasOne/hasMany, example:

Car hasMany Components
Component belongsTo Car
$component->car_id = $car->id
cascading will be defined in Car because component depends on car and not the opposite.

2018-05-03 14:54 UTC, gcphost commented
Your call @maguilar92 on that.

This PR has a lot of `Immofacile` name space changes, I didn't see that before. It'll have to be rejected.

2018-05-03 15:05 UTC, closed without merging